services:
  postgres:
    image: postgres:16
    container_name: enedis-retriever-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: enedis_retriever
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - enedis-retriever-postgres-data:/var/lib/postgresql/data

  enedis-retriever:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: enedis-retriever
    ports:
      - "5000:8080"
    env_file:
      - .env.docker.development
    volumes:
      - ./EnedisRetriever:/src/EnedisRetriever
    depends_on:
      - postgres

volumes:
  enedis-retriever-postgres-data: