FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

COPY EnedisRetriever/EnedisRetriever.csproj EnedisRetriever/

RUN dotnet restore EnedisRetriever/EnedisRetriever.csproj

COPY EnedisRetriever/ EnedisRetriever/

WORKDIR /src/EnedisRetriever

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://0.0.0.0:8080"]
