@host = https://localhost:7290
@start = 2026-10-30
@end = 2026-09-03

### Get raw consumption points
GET {{host}}/api/consumption?start={{start}}&end={{end}}


### Get consumption summary
GET {{host}}/api/consumption/summary?start={{start}}&end={{end}}


### Aggregate - 30 minutes
GET {{host}}/api/consumption/aggregate?start={{start}}&end={{end}}&granularity=HalfHour


### Aggregate - Hour
GET {{host}}/api/consumption/aggregate?start={{start}}&end={{end}}&granularity=Hour


### Aggregate - Day
GET {{host}}/api/consumption/aggregate?start={{start}}&end={{end}}&granularity=Day


### Aggregate - Week
GET {{host}}/api/consumption/aggregate?start={{start}}&end={{end}}&granularity=Week


### Aggregate - Month
GET {{host}}/api/consumption/aggregate?start={{start}}&end={{end}}&granularity=Month


### Aggregate - Year
GET {{host}}/api/consumption/aggregate?start={{start}}&end={{end}}&granularity=Year